
name: topup_game_murah
description: Aplikasi top-up game murah dengan tema neon.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
